In [ ]:
"""
Introduction to Numpy and LaTeX
(Created for UBC Engineering Physics 259)

@authors: Alexandra Tully, Tim Child
@date: 30 July 2020
""";

## Numpy Arrays

There are several great libraries in Python for working with data, most notably Numpy and Pandas. Here we will look at the most popular and a common starting place, Numpy. (Pandas builds on top of Numpy and they work together very well).

The Numpy package provides many of the same functions as found in Matlab, plus many many more. 

To use Numpy, the numpy package must first be imported into the script using an import statement. It is common to import numpy like this: `import numpy as np`. The as `np` part just makes it quicker to type when using later. As with all import statements, they need only be run once, but it doesn't hurt to run them multiple times.

e.g.
```
import numpy as np
xdata = np.array([1,2,3,4,5,6,7,8])
```
To create a numpy array from scratch. Or
```
xdata = np.linspace(0, 100, 1000)  # Creates a 1D array with 1000 values from 0 -> 100
ydata = np.sin(xdata)  # Creates a 1D array with sin(x) evaluated at each xdata value
```

The Numpy package has extremely good documentation which can be found [here](https://numpy.org/doc/stable/user/absolute_beginners.html). 

Additionally, any question you might have that doesn't have an obvious answer in the documentation has 99.9% of the time, been asked on StackOverflow (https://stackoverflow.com/) already, and the answers are usually extremely helpful. (Seriously, the effort people have put into answering questions about all things Python is incredible). 

### Viewing data in arrays

It's often useful to get a quick idea of what values are in an array, even before plotting. A couple of ways are:

1. Leave the array as the last line of a cell and run it


In [ ]:
import numpy as np
x = np.linspace(-3, 7, 11)
x

array([-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.])

2. Print the array anywhere in the cell

In [ ]:
y = x**2  # Double star means 'to power of'
print(y)
y = y*3  
print(y)

[ 9.  4.  1.  0.  1.  4.  9. 16. 25. 36. 49.]
[ 27.  12.   3.   0.   3.  12.  27.  48.  75. 108. 147.]


### Retrieving Specific Values

It's often useful to find values, or where values are in arrays of data. 

Here I'll go over just a few examples, if you still have questions, StackOverflow is your friend!


In [ ]:
#  Making some sample data
x = np.linspace(-10, 10, 1000)  
y = 2.1*x**2 -17.6*x + 14.3 

# Now I want to find the minimum y value and store it in a variable called 'y_min'
y_min = np.min(y)  

# If I want to find the index of the array at which it is minimum, then I would argmin instead
y_min_index = np.argmin(y) 
print(f'The index at y_min is = {y_min_index}')  # remember f' ' makes a format string

# Then I could use that index to find out what the x value was at the minimum y value
print(f'y has a minimum value of {y_min:.2f} at x = {x[y_min_index]:.2f}')


The index at y_min is = 709
y has a minimum value of -22.58 at x = 4.19


## LaTeX / Equations in Python

LaTeX is a widely used formatting scripting language called LaTeX (or Tex) which is superior to render mathematical expressions and is used widely. It's definitely worth learning ASAP.

To insert an expression wrap the LaTeX formatted equation in either `$` signs for inline equations, or `$$` for full line equations

e.g. If you enter

`$$\alpha^2+\beta^2=c^2$$`

This is the result: 
$$\alpha^2+\beta^2=c^2$$

Single `$` signs allow you to put equations in the $\alpha^2+\beta^2=c^2$ middle of sentences.

Go to https://www.codecogs.com/latex/eqneditor.php or https://www.latex4technics.com/ for help with writing LaTeX equations.

Here is an example of a more complicated formula,

`$$P_\lambda = \frac{2 \pi h c^2}{\lambda^5 \left(e^{\left(\frac{h c}{\lambda k T}\right)} - 1\right)}$$`
$$P_\lambda = \frac{2 \pi h c^2}{\lambda^5 \left(e^{\left(\frac{h c}{\lambda k T}\right)} - 1\right)}$$